### PR TITLE
Add schema name support (#101)

### PR DESCRIPTION
**Pull request by tunger**
Adds support for the schema name which can be configured on DocumentMap.

Please have a look if this conforms with your ideas, or if something is missing, like more tests or such.
I didn't quite grasp how the related document mappings work (as I haven't used the library much yet). If you can give me a hint how it works, I could add the schema name there as well.

### CODE REVIEW

**Comment by tunger** [comment]
By the way, the CLA Assistant seems not to work, can't sign anything on the provided page.

**Comment by PaulStovell** [comment]
Nice! I will take a deeper look tomorrow but I like what I have seen so far.

I am thinking about a way to catch places where we forget to specify the schema. Maybe we can change or drop the default schema in the test database, which will cause any queries that omit the schema to fail? Might play around with it tomorrow. 

I also think it would be helpful if the default schema could be specified on the configuration object, and inherited into the document maps. 

I’ll sort out the CLA thing too.

**Comment by PaulStovell** [comment]
I just checked the CLA link. It takes a little while, but eventually it does show the CLA and a button to sign. Do you see it if you try again?

**Comment by tunger** [comment]
Ah you are right, done, looks like I was too impatient 😉
I will have time later to work on the code again based on your comment.

**Comment by PaulStovell** [comment]
I've reviewed and am ready to merge it! I also changed the integration tests so that they all use a schema - this caught a few places we weren't dealing with schemas. 🙇 Thank you for the PR! 

Once the CLA thing is sorted we can merge it. Let me know if you still have trouble with the CLA and I'll email a document over?

**Comment by tunger** [comment]
Oh great, thanks! :)
You are welcome!
I rebased onto master and force pushed changes, as I didn't see commits from you on the branch, and removed draft status. So nothing left to do for me? ;)

CLA did work out, see previous comment, thanks!

**Comment by PaulStovell** [comment]
Done! I manually merged this into `master`. We'll push a new release to NuGet shortly.

**Comment by PaulStovell** [comment]
It's published to NuGet as 12.6.1. 

You can either set the schema on the `DocumentMap`, or on the `IRelationalStore` there is a `DefaultSchema` which is used as the default.

**Comment by tunger** [comment]
Thanks, works good, starting to use it already :)
There seems to be an issue when setting it in configuration, I will have a look at it when I have time. Via the maps works fine though.

**Pull request closed without merging**
